name: reddit_clone
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  firebase_storage: ^11.2.6
  cloud_firestore: ^4.9.1
  google_sign_in: ^6.1.5
  flutter_riverpod: ^2.4.0
  fpdart: ^1.1.0
  routemaster: ^1.0.1
  dotted_border: ^2.1.0
  file_picker: ^6.0.0
  # firebase_messaging: ^14.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/awards/
