// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBstU0BJ3H4wIjHKDSM_amN7vzx9ixyQW0',
    appId: '1:126799334068:web:d768506edc1e19a8f2a5e1',
    messagingSenderId: '126799334068',
    projectId: 'reddit-clone-ved',
    authDomain: 'reddit-clone-ved.firebaseapp.com',
    storageBucket: 'reddit-clone-ved.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBMEXLEIIbiVhcV0RMxKZgefnpBT9dq9A',
    appId: '1:126799334068:android:1d6beecbcb5862fef2a5e1',
    messagingSenderId: '126799334068',
    projectId: 'reddit-clone-ved',
    storageBucket: 'reddit-clone-ved.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbbVG5gbGEJ4e9hQcj1acCsSLSUsS2C_w',
    appId: '1:126799334068:ios:b9764d93eb925fe4f2a5e1',
    messagingSenderId: '126799334068',
    projectId: 'reddit-clone-ved',
    storageBucket: 'reddit-clone-ved.appspot.com',
    iosClientId: '126799334068-rodpqisvu7jdt06jr71g0dvej2ilg5g9.apps.googleusercontent.com',
    iosBundleId: 'com.codeconline.redditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbbVG5gbGEJ4e9hQcj1acCsSLSUsS2C_w',
    appId: '1:126799334068:ios:e521e020650c9d24f2a5e1',
    messagingSenderId: '126799334068',
    projectId: 'reddit-clone-ved',
    storageBucket: 'reddit-clone-ved.appspot.com',
    iosClientId: '126799334068-qne1v113lauct4jcnamodnnd3caf831b.apps.googleusercontent.com',
    iosBundleId: 'com.codeconline.redditClone.RunnerTests',
  );
}
